site_name: AuraAuth
site_description: Next-Gen 2FA Security. Sleek. Secure. Liquid Glass UI.
theme:
  name: readthedocs

nav:
  - Home: index.md
  # You can add more pages later like this:
  # - Setup Guide: setup.md
  # - Privacy Policy: privacy.md
